apiVersion: v1
kind: ReplicationController
metadata:
  name: conda
spec:
  replicas: 1
  selector:
    role: data-analytics
  template:
    metadata:
      labels:
        role: data-analytics
    spec:
      containers:
      - name: conda
        image: continuumio/anaconda3
        command: ["/bin/ls"]
        ports:
          - name: jupyter
            containerPort: 8888
        volumeMounts:
            # name must match the volume name below
            - name: conda-volume
              mountPath: "/opt/notebooks"
      volumes:
      - name: conda-volume
        persistentVolumeClaim:
          claimName: conda-claim

